import { Member } from '@src/types';

export const members: Member[] = [
  {
    id: 'ararajp',
    nickname: 'あらら',
    realName: '荒井勇輔',
    bio: 'VPoE',
    avatarSrc: '/avatars/ararajp.jpeg',
    sources: ['https://note.com/ararajp/rss'],
    twitterUsername: 'arara_jp',
    githubUsername: 'ararajp',
    websiteUrl: 'https://note.com/ararajp/',
  },
  {
    id: 'ikenyal',
    nickname: 'ikenyal',
    realName: '池田健人',
    bio: 'Engineering Manager',
    avatarSrc: '/avatars/ikenyal.jpeg',
    sources: ['https://qiita.com/ikenyal/feed', 'https://zenn.dev/ikenyal/feed', 'https://dev.to/feed/ikenyal'],
    twitterUsername: 'ikenyal',
    githubUsername: 'ikenyal',
    websiteUrl: 'https://zenn.dev/ikenyal',
  },
  {
    id: '7kaji',
    nickname: '7kaji',
    realName: '中島裕聡',
    bio: 'Engineer',
    avatarSrc: '/avatars/7kaji.png',
    sources: ['https://zenn.dev/7kaji/feed'],
    twitterUsername: '7kajii',
    githubUsername: '7kaji',
    websiteUrl: 'https://zenn.dev/7kaji',
  },
  {
    id: 'kotatsu360',
    nickname: 'kotatsu360',
    realName: '光野達朗',
    bio: 'SRE',
    avatarSrc: '/avatars/kotatsu360.png',
    sources: ['https://qiita.com/kotatsu360/feed'],
    twitterUsername: 'kotatsu360',
    githubUsername: 'kotatsu360',
    websiteUrl: 'https://qiita.com/kotatsu360',
  },
  {
    id: 'ring',
    nickname: 'ring',
    realName: '名取弘平',
    bio: 'Engineer',
    avatarSrc: '/avatars/ring.jpeg',
    sources: ['https://zenn.dev/natoring/feed'],
    twitterUsername: 'nato_ring',
    githubUsername: 'natoring',
    websiteUrl: 'https://qiita.com/ahiru___',
  },
  {
    id: 'kommy',
    nickname: 'kommy',
    realName: '小宮山紘平',
    bio: 'Data Engineer',
    avatarSrc: '/avatars/kommy.jpeg',
    sources: ['https://zenn.dev/kommy339/feed'],
    twitterUsername: 'kommy_jp',
    githubUsername: 'momatan',
    websiteUrl: 'https://zenn.dev/kommy339',
  },
  {
    id: 'nishisuke',
    nickname: 'にっしー',
    realName: '西上良祐',
    bio: 'Tech Lead - Go, React, Flutter',
    avatarSrc: '/avatars/nishisuke.jpeg',
    sources: ['https://zenn.dev/nishisuke/feed'],
    twitterUsername: '_nishisuke',
    githubUsername: 'nishisuke',
    websiteUrl: 'https://zenn.dev/nishisuke',
  },
  {
    id: 'kajidai',
    nickname: 'kajidai',
    realName: '梶原大輔',
    bio: 'CTO',
    avatarSrc: '/avatars/kajidai.jpeg',
    //sources: [''],
    twitterUsername: 'kajidai',
    githubUsername: 'kajidai',
    //websiteUrl: '',
  },
  {
    id: 'geshi',
    nickname: 'geshi',
    realName: '重村裕紀',
    bio: 'CPO',
    avatarSrc: '/avatars/geshi.jpeg',
    sources: ['https://note.com/geshi1/rss'],
    twitterUsername: 'geshi0123',
    githubUsername: 'geshigenda',
    websiteUrl: 'https://note.com/geshi1',
  },
  {
    id: 'tochiba',
    nickname: 'ばーちー',
    realName: '千葉俊輝',
    bio: 'Product Manager',
    avatarSrc: '/avatars/tochiba.jpeg',
    sources: ['https://note.com/tochiba/rss'],
    twitterUsername: '104kn',
    githubUsername: 'tochiba',
    websiteUrl: 'https://note.com/tochiba',
  },
  {
    id: 'miyatake',
    nickname: 'miyatake',
    realName: '宮武聖一郎',
    bio: 'Marketing',
    avatarSrc: '/avatars/miyatake.jpeg',
    //sources: [''],
    twitterUsername: 'smiyatake_',
    //githubUsername: '',
    //websiteUrl: '',
  },
  {
    id: 'WorldDownTown',
    nickname: 'WorldDownTown',
    realName: '庄司啓輔',
    bio: 'Engineer',
    avatarSrc: '/avatars/worlddowntown.jpeg',
    sources: ['https://qiita.com/WorldDownTown/feed', 'https://zenn.dev/worlddowntown/feed'],
    twitterUsername: 'WorldDownTown',
    githubUsername: 'WorldDownTown',
    websiteUrl: 'https://qiita.com/WorldDownTown',
  },
  {
    id: 'namiki',
    nickname: 'なみき',
    realName: '木村奈美',
    bio: 'Engineer',
    avatarSrc: '/avatars/namiki.png',
    sources: ['https://namikiwi.hatenablog.com/feed'],
    twitterUsername: 'sasaki445',
    githubUsername: 'namiki64',
    websiteUrl: 'https://namikiwi.hatenablog.com',
  },
  {
    id: 'yamaguchi',
    nickname: 'yamaguchi',
    realName: '山口歩夢',
    bio: 'Data Engineer',
    avatarSrc: '/avatars/yamaguchi.jpeg',
    sources: ['https://qiita.com/Ayumu-y/feed'],
    twitterUsername: 'Yamaguchi_aaaaa',
    githubUsername: 'gussan-me',
    websiteUrl: 'https://qiita.com/Ayumu-y',
  },
  {
    id: 'tomatsu',
    nickname: 'tomatsu',
    realName: '戸松真太朗',
    bio: 'Data Scientist',
    avatarSrc: '/avatars/tomatsu.jpeg',
    sources: ['https://zenn.dev/toma2/feed'],
    // twitterUsername: '',
    githubUsername: 'tomatsuShi',
    websiteUrl: 'https://zenn.dev/toma2',
  },
  {
    id: 'matsumura',
    nickname: 'matsumura',
    realName: '松村聡士',
    bio: 'Engineer',
    avatarSrc: '/avatars/smatsumura.png',
    sources: ['https://wordpress.nazoweb.com/feed'],
    // twitterUsername: '',
    // githubUsername: '',
    websiteUrl: 'https://wordpress.nazoweb.com/',
  },
  {
    id: 'shinnoki',
    nickname: 'shinnoki',
    realName: '進木裕大',
    bio: 'FE/BE Engineer',
    avatarSrc: '/avatars/shinnoki.jpeg',
    sources: ['https://zenn.dev/shinnoki/feed', 'https://qiita.com/shinnoki/feed'],
    twitterUsername: 'y_shinnoki',
    githubUsername: 'shinnoki',
    websiteUrl: 'https://zenn.dev/shinnoki',
  },
  {
    id: 'kinako',
    nickname: 'kinako',
    realName: '大河内明日香',
    bio: 'Product Manager',
    avatarSrc: '/avatars/kinako.jpeg',
    sources: ['https://note.com/asuka_okochi_131/rss'],
    twitterUsername: 'asukaokochi',
    githubUsername: 'asukaokochi',
    websiteUrl: 'https://note.com/asuka_okochi_131',
  },
  {
    id: 'ken2403',
    nickname: 'ken2403',
    realName: '西尾健人',
    bio: 'Engineer',
    avatarSrc: '/avatars/ken2403.jpeg',
    sources: ['https://zenn.dev/ken2403/feed'],
    // twitterUsername: '',
    githubUsername: 'ken2403',
    websiteUrl: 'https://zenn.dev/ken2403',
  }
].sort((a, b) => (a.nickname < b.nickname ? -1 : 1));
